# Generated by Django 2.2.1 on 2019-12-18 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('pno', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=40)),
                ('pinfo', models.TextField()),
                ('image', models.FileField(upload_to='products/')),
                ('bprice', models.FloatField()),
                ('status', models.CharField(max_length=40)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.RegisterModel')),
            ],
        ),
    ]
