# Generated by Django 2.2.1 on 2019-12-19 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_productmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidtableModel',
            fields=[
                ('bid', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('pno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ProductModel')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.RegisterModel')),
            ],
        ),
    ]
