# Generated by Django 2.2.1 on 2019-12-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_bidtablemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidtablemodel',
            name='bid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
